const express = require('express')
const router = express.Router()
const userController = require('./../controllers/userController')
const { auth } = require('./../middleware/userAuth')
const { emailAuth } = require('./.././middleware/emailAuth')
const upload = require('./../middleware/ImageUpload')
router.post('/signup', userController.signup)
router.post('/login', emailAuth, userController.login)
router.get('/', auth, userController.getAllUsers)
router.get('/:id', auth, userController.getUser)
router.get('/verify_email', userController.verifyEmail)
router.delete('/:id', auth, userController.deleteUser)
router.patch('/:id', auth, userController.updateUser)
router.post('/uploadImage', upload.single('file'), userController.uploadImage)
router.get('/image/:filename', userController.getImage)
module.exports = router
